spring.application.name=proj6_java

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mariadb://${MYSQL_HOST:localhost}:3306/proj6db
spring.datasource.username=proj6user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
